title: Roti Proa
description: Solar-electric proa designs and documentation
theme: jekyll-theme-cayman
baseurl: /CAD

# Build settings
markdown: kramdown

# Include the renders directory
include:
  - renders
